Increment seventeen
serjyuriev/shortener pull request #16
Opened 2022-06-01 18:38 UTC by serjyuriev

2022-06-01 18:40 UTC, serjyuriev commented
Добавил в PR только коммиты седьмого спринта.

2022-06-05 22:55 UTC, Barugoo commented on internal/pkg/handlers/handlers_test.go
> +func BenchmarkPostURLHandler(b *testing.B) {
Бенчмарки предназначены для тестирования производительности CPU-bound задач, которые включают: математические вычисления (например хэширование), операции над коллекциями (поиск, вставка, удаление и тд). В нашем случае можно сделать две реализации хранилки урлов - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях.

2022-06-05 22:56 UTC, Barugoo commented on internal/pkg/handlers/handlers_test.go
> +// func BenchmarkPostBatchHandler(b *testing.B) {
Давай не оставлять закомменченный код в репе

2022-06-05 22:57 UTC, Barugoo commented on internal/pkg/handlers/handlers.go
> +func MakeHandlers() (*Handlers, error) {
Не вижу эндпоинтов для `pprof` или импортированного `net/http/pprof`

2022-06-05 22:57 UTC, Barugoo requested changes
Не вижу примеров использования пакетов, надо бы добавить бенчмарки и впилить профилировщик

2022-06-10 07:30 UTC, Barugoo approved these changes
Отлично!

2022-06-10 08:08 UTC, merged