Increment seven
serjyuriev/shortener pull request #7
Opened 2022-02-26 09:29 UTC by serjyuriev

2022-03-02 13:01 UTC, Barugoo commented on cmd/shortener/main.go
> +}
Давай перенесем этот код в начало `main`
Лучше не использовать `init` без необходимости

2022-03-02 13:02 UTC, Barugoo commented on cmd/shortener/main.go
> +		cfg.BaseURL = fmt.Sprintf("http://%s", cfg.ServerAddress)
Давай утащим протокол в конфиг, на случай если захотим подрубить TLS (http->https) на сервере:
```go
cfg.BaseURL = cfg.ServerAddress // cfg.ServerAddress = http://localhost:8080
```

2022-03-02 13:03 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Fatal(err)
Давай добавим какое-нибудь пояснение к ошибке, чтобы девопсы смогли разобраться почему сервер может не стартовать:
```go
log.Fatalf("unable to start server: %v", err)
```
В остальных местах тоже

2022-03-02 13:06 UTC, Barugoo commented on internal/pkg/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Давай клиенту возвращать более абстрактную ошибку, чтобы скрывать реализацию сервера, а реальную ошибку логгировать:
```go
log.Printf("unable to save url: %v\n", err)
http.Error(w, "internal server error", http.StatusInternalServerError)

2022-03-02 13:07 UTC, Barugoo commented on internal/pkg/handlers/handlers.go
> +	if err := Store.InsertNewURLPair(storage.ShortPath(s), storage.LongURL(req.URL)); err != nil {
Мне кажется нет особого смысла делать переопределения типов ShortPath и LongURL
Сделай просто строками, тогда преведения типов делать не нужно будет везде

2022-03-02 13:12 UTC, Barugoo commented on internal/pkg/storage/file.go
> +	return <-e
Насколько я понимаю, если не удасться сохранить здесь урл в файл, то в мапке он все равно появится. При этом ты вернешь ошибку клиенту и он будет думать, что урл не создался, когда на самом деле ты его сохранил в память.
Если ты хочешь игнорировать ошибку с файлом, но при этом чтобы данные точно сохранились в мапку ты можешь просто логгировать ошибку записи в файл, при этом записывая в мапку и возвращая `nil` вв качестве ошибки

2022-03-02 13:14 UTC, Barugoo commented on internal/pkg/storage/file.go
> +	data = append(data, '\n')
По-моему это не очень удобный способ хранить урлы на диске. Что если нам понадобится точечно удалить определенный урл из файла? Нам придется делать велосипеды для функционала поиска по файлу, а хотелось бы без них.
Я предлагаю при каждой вставке, удалении и так далее сериализовать мапку в джейсон и целиком перезаписывать содержимое файла. И это кстати уже можно делать асинхронно (в хэндлере сделали изменение в мапке - послали хранилке сигнал о том что нужно перезаписать файл обновленной мапкой)

2022-03-02 13:15 UTC, Barugoo requested changes
Хорошо, но есть замечания

2022-03-02 18:32 UTC, serjyuriev commented
Исправил большую часть замечаний.
Протокол утащил в конфиг отдельным флагом, потому что по другому не получилось.

Асинхронность пока убрал вообще, потому что подумал (и возможно я тут не прав), если хендлер создания нового УРЛа будет вызван дважды в очень короткий промежуток времени, то может же случиться такое, что файл будет открыт первым вызовом, поэтому второй, попытаясь открыть его, упадет. Наверно надо будет наворачивать sync библиотеку, которая у нас, скорее всего, в 4 спринте еще будет.

2022-03-04 20:27 UTC, Barugoo commented on internal/pkg/storage/storage.go
> +	FindLongURL(sp string) (string, error)
Не совсем понятно, что такое `sp`
Лучше в сигнатурах методов интерфейса не экономить символы:
```go
type Store interface {
	FindLongURLByShort(shortPath string) (string, error)
```

2022-03-04 20:29 UTC, Barugoo approved these changes
Отлично!

2022-06-01 18:34 UTC, merged